'use client'

import Link from "next/link";
import { useState } from "react";
import { submitReport } from "@/actions/reportActions";
import { logoutAction } from "@/actions/authActions";
import jsPDF from "jspdf";

export default function AnalystDashboard() {
  const [loading, setLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setLoading(true);
    const formData = new FormData(e.currentTarget);
    const res = await submitReport(formData) as any;
    if (res?.success) {
      setSubmitted(true);
      setTimeout(() => setSubmitted(false), 5000);
      (e.target as HTMLFormElement).reset();
    } else {
      alert("Error: " + res?.error);
    }
    setLoading(false);
  }

  const generateDynamicPdf = () => {
    const form = document.getElementById('analyst-form') as HTMLFormElement;
    if (!form) return;
    const fd = new FormData(form);
    
    // Helper to get form values safely
    const g = (k: string) => fd.get(k) as string || '0';

    const companyA = g('companyA_name');
    const companyB = g('companyB_name');
    const doc = new jsPDF();

    if (!companyA || companyA === '0' || !companyB || companyB === '0') {
      alert("Please enter company names before exporting.");
      return;
    }

    // --- Header Branding ---
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, 210, 32, 'F');
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22); doc.setTextColor(255, 255, 255);
    doc.text("FinAn", 15, 20);
    doc.setFontSize(8); doc.setTextColor(150, 150, 150);
    doc.text("INVESTMENT BANKING — CONFIDENTIAL MODEL EXPORT", 50, 20);
    doc.text(`DATE: ${new Date().toLocaleDateString()}`, 160, 20);

    let y = 45;
    doc.setTextColor(30, 30, 30);

    // --- Title ---
    doc.setFontSize(16);
    doc.text(`Strategic M&A Analysis: ${companyA} + ${companyB}`, 15, y); 
    y += 4;
    doc.setDrawColor(200, 200, 200); doc.line(15, y, 195, y); 
    y += 12;

    // --- Section: Acquirer ---
    doc.setFontSize(12); doc.setTextColor(41, 151, 255);
    doc.text(`ACQUIRER: ${companyA.toUpperCase()}`, 15, y); 
    y += 8;
    doc.setTextColor(60, 60, 60); doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    
    const acquirerData = [
      ['Current Share Price', `Rs. ${g('companyA_price')}`],
      ['Shares Outstanding', `${g('companyA_shares')} M`],
      ['Annual Revenue', `Rs. ${g('companyA_revenue')} M`],
      ['Annual EBITDA', `Rs. ${g('companyA_ebitda')} M`],
      ['Net Income', `Rs. ${g('companyA_netIncome')} M`],
      ['Total Net Debt', `Rs. ${g('companyA_netDebt')} M`],
    ];
    acquirerData.forEach(([label, val]) => {
      doc.text(label, 20, y); doc.text(val, 100, y); y += 7;
    });
    y += 6;

    // --- Section: Target ---
    doc.setFontSize(12); doc.setTextColor(255, 159, 10);
    doc.text(`TARGET: ${companyB.toUpperCase()}`, 15, y); 
    y += 8;
    doc.setTextColor(60, 60, 60); doc.setFontSize(10);
    const targetData = [
      ['Current Share Price', `Rs. ${g('companyB_price')}`],
      ['Shares Outstanding', `${g('companyB_shares')} M`],
      ['Annual Revenue', `Rs. ${g('companyB_revenue')} M`],
      ['Annual EBITDA', `Rs. ${g('companyB_ebitda')} M`],
      ['Net Debt', `Rs. ${g('companyB_netDebt')} M`],
    ];
    targetData.forEach(([label, val]) => {
      doc.text(label, 20, y); doc.text(val, 100, y); y += 7;
    });
    y += 8;

    // --- Section: Assumptions ---
    doc.setDrawColor(220, 220, 220); doc.line(15, y, 195, y); y += 10;
    doc.setFontSize(12); doc.setTextColor(50, 50, 50);
    doc.text("VALUATION & DEAL ASSUMPTIONS", 15, y); 
    y += 10;
    doc.setFontSize(10);
    
    const assumptions = [
      ['WACC (Discount Rate)', `${g('wacc')}%`],
      ['Terminal Growth Rate', `${g('tgr')}%`],
      ['Revenue Growth (Est.)', `${g('revenueGrowth')}%`],
      ['Tax Rate', `${g('taxRate')}%`],
      ['Offer Premium', `${g('premium')}%`],
      ['Cash Consideration', `${g('cashPct')}%`],
    ];
    assumptions.forEach(([label, val]) => {
      doc.text(label, 20, y); doc.text(val, 100, y); y += 7;
    });

    // --- Footer ---
    doc.setFillColor(248, 248, 250);
    doc.rect(0, 275, 210, 22, 'F');
    doc.setFontSize(8); doc.setTextColor(140, 140, 140);
    doc.text("This document is generated by FinAn AI Financial Systems. Values are for analytical purposes only.", 15, 285);
    doc.text("Proprietary and Confidential.", 15, 290);

    doc.save(`${companyA}_M&A_Report.pdf`);
  }

  return (
    <div className="dashboard-layout">
      {/* Sidebar */}
      <aside className="sidebar">
        <div className="sidebar-brand">
          <h2><span className="text-gradient-blue">FinAn</span></h2>
          <p>Analyst Workspace</p>
        </div>
        <nav className="sidebar-nav">
          <Link href="/analyst" className="sidebar-link active">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>
            New Analysis
          </Link>
          <Link href="/analyst/history" className="sidebar-link">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>
            My Reports
          </Link>
          <Link href="/analyst/chat" className="sidebar-link">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" /></svg>
            Intelligent Analysis Engine
          </Link>
        </nav>
        <div className="sidebar-footer">
          <form action={logoutAction}><button className="btn btn-secondary" style={{ width: '100%', fontSize: '13px' }}>Sign Out</button></form>
        </div>
      </aside>

      {/* Main Content */}
      <main className="main-content">
        <div className="page-header animate-fade-in">
          <h1 className="text-gradient">Financial Modeling</h1>
          <p>Build comprehensive M&A and DCF valuation models for strategic decision making.</p>
        </div>

        {submitted && (
          <div className="animate-fade-in" style={{
            background: 'rgba(48, 209, 88, 0.08)', border: '1px solid rgba(48, 209, 88, 0.2)',
            color: 'var(--accent-success)', padding: '14px 20px', borderRadius: 'var(--radius-sm)',
            marginBottom: '24px', fontSize: '14px', fontWeight: 500,
          }}>✓ Report submitted to banker review queue.</div>
        )}

        <form id="analyst-form" onSubmit={handleSubmit}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
            {/* Acquirer */}
            <div className="glass-panel animate-fade-in" style={{ padding: '28px' }}>
              <h3 style={{ fontSize: '15px', fontWeight: 600, marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--accent-primary)' }} /> Acquirer Details
              </h3>
              <div className="input-group">
                <label className="input-label">Company Name</label>
                <input name="companyA_name" type="text" className="input-field" placeholder="e.g. Reliance" required />
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div className="input-group"><label className="input-label">Share Price (₹)</label><input name="companyA_price" type="number" step="0.01" className="input-field" placeholder="1000" required /></div>
                <div className="input-group"><label className="input-label">Shares Out. (M)</label><input name="companyA_shares" type="number" className="input-field" placeholder="500" required /></div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div className="input-group"><label className="input-label">Revenue (₹M)</label><input name="companyA_revenue" type="number" className="input-field" placeholder="5000" required /></div>
                <div className="input-group"><label className="input-label">EBITDA (₹M)</label><input name="companyA_ebitda" type="number" className="input-field" placeholder="1200" required /></div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div className="input-group"><label className="input-label">Net Income (₹M)</label><input name="companyA_netIncome" type="number" className="input-field" placeholder="800" required /></div>
                <div className="input-group"><label className="input-label">Net Debt (₹M)</label><input name="companyA_netDebt" type="number" className="input-field" placeholder="2000" required /></div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '12px' }}>
                <div className="input-group"><label className="input-label">CapEx (₹M)</label><input name="companyA_capex" type="number" className="input-field" placeholder="300" required /></div>
                <div className="input-group"><label className="input-label">D&A (₹M)</label><input name="companyA_da" type="number" className="input-field" placeholder="200" required /></div>
                <div className="input-group"><label className="input-label">ΔNWC (₹M)</label><input name="companyA_nwcChange" type="number" className="input-field" placeholder="50" required /></div>
              </div>
            </div>

            {/* Target */}
            <div className="glass-panel animate-fade-in" style={{ padding: '28px' }}>
              <h3 style={{ fontSize: '15px', fontWeight: 600, marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--accent-orange)' }} /> Target Details
              </h3>
              <div className="input-group"><label className="input-label">Company Name</label><input name="companyB_name" type="text" className="input-field" placeholder="e.g. Zomato" required /></div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div className="input-group"><label className="input-label">Share Price (₹)</label><input name="companyB_price" type="number" step="0.01" className="input-field" required /></div>
                <div className="input-group"><label className="input-label">Shares Out. (M)</label><input name="companyB_shares" type="number" className="input-field" required /></div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div className="input-group"><label className="input-label">Revenue (₹M)</label><input name="companyB_revenue" type="number" className="input-field" required /></div>
                <div className="input-group"><label className="input-label">EBITDA (₹M)</label><input name="companyB_ebitda" type="number" className="input-field" required /></div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div className="input-group"><label className="input-label">Net Income (₹M)</label><input name="companyB_netIncome" type="number" className="input-field" required /></div>
                <div className="input-group"><label className="input-label">Net Debt (₹M)</label><input name="companyB_netDebt" type="number" className="input-field" required /></div>
              </div>
            </div>
          </div>

          <div className="glass-panel" style={{ padding: '28px', marginTop: '20px' }}>
             <h3 style={{ fontSize: '15px', marginBottom: '20px' }}>Valuation Assumptions</h3>
             <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '12px' }}>
                <div className="input-group"><label className="input-label">WACC (%)</label><input name="wacc" type="number" step="0.1" className="input-field" defaultValue="9" required /></div>
                <div className="input-group"><label className="input-label">TGR (%)</label><input name="tgr" type="number" step="0.1" className="input-field" defaultValue="2.5" required /></div>
                <div className="input-group"><label className="input-label">Growth (%)</label><input name="revenueGrowth" type="number" step="0.1" className="input-field" defaultValue="5" required /></div>
                <div className="input-group"><label className="input-label">Margin (%)</label><input name="ebitdaMargin" type="number" step="0.1" className="input-field" defaultValue="25" required /></div>
                <div className="input-group"><label className="input-label">Tax (%)</label><input name="taxRate" type="number" step="0.1" className="input-field" defaultValue="25" required /></div>
                <div className="input-group"><label className="input-label">Years</label><input name="projectionYears" type="number" className="input-field" defaultValue="5" required /></div>
             </div>
          </div>

          <div className="glass-panel" style={{ padding: '28px', marginTop: '20px' }}>
             <h3 style={{ fontSize: '15px', marginBottom: '20px' }}>Deal Structure</h3>
             <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '12px' }}>
                <div className="input-group"><label className="input-label">Premium (%)</label><input name="premium" type="number" step="0.1" className="input-field" defaultValue="20" required /></div>
                <div className="input-group"><label className="input-label">Cash Mix (%)</label><input name="cashPct" type="number" className="input-field" defaultValue="50" required /></div>
                <div className="input-group"><label className="input-label">Cost Syn (₹M)</label><input name="costSynergies" type="number" className="input-field" defaultValue="50" required /></div>
                <div className="input-group"><label className="input-label">Rev Syn (₹M)</label><input name="revenueSynergies" type="number" className="input-field" defaultValue="0" required /></div>
                <div className="input-group"><label className="input-label">Integ. (₹M)</label><input name="integrationCosts" type="number" className="input-field" defaultValue="20" required /></div>
                <div className="input-group"><label className="input-label">Debt (%)</label><input name="debtFinancingRate" type="number" step="0.1" className="input-field" defaultValue="5" required /></div>
             </div>
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '24px' }}>
            <button type="button" onClick={generateDynamicPdf} className="btn btn-secondary">Export Model PDF</button>
            <button type="submit" className="btn btn-accent" disabled={loading}>{loading ? 'Submitting...' : 'Submit to Banker →'}</button>
          </div>
        </form>
      </main>
    </div>
  );
}
