# FastAPI Backend Dockerfile
FROM python:3.11-slim
WORKDIR /app

# Copy requirement and install
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY backend/ .

# Expose port and run server
ENV PORT=10000
EXPOSE ${PORT}
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT}"]
